project:
  type: website

website:
  title: "Cross Sections, Quantum Yields, and Photolysis Rates"
  search: true
  navbar:
    background: primary
    right:
      - text: "Home"
        file: index.qmd
      - text: "Cross Sections"
        file: cross_sections.qmd
      - text: "Quantum Yields"
        file: quantum_yields.qmd

  sidebar:
    - title: "Cross Sections"
      style: "docked"
      background: light
      search: true
      contents:
        - cross_sections.qmd
        - cross_sections/O3.ipynb
        - cross_sections/H2O2.ipynb
        - cross_sections/NO2.ipynb
        - cross_sections/NO3.ipynb
        - cross_sections/HONO.ipynb
        - cross_sections/CH2O.ipynb
        - cross_sections/HONO2.ipynb

    - title: "Quantum Yields"
      style: "docked"
      background: light
      search: true
      contents:
        - quantum_yields.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

reference-location: margin
citation-location: margin

